// Code generated by alef — DO NOT EDIT.
// alef:hash:11029f77610be79902ae2fb2de4e5eb6c6ecfa39ef490d24baba77f1e38f27bd
package htmltomarkdown

// RequireNativeSetup_3_12_3 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_12_3 = "3.12.3"
