# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc524cd24840e9205c5f1e9a5429f00d3b9c390ae1decedd74ea0dabc8973dee
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.12.3"
end
