// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:078d9a084ab6f8106f5fff24f535ff71b0055a107bf68ecc77ddf90e6575affd
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>FFI JSON serialization extension methods and options</summary>
internal static class FfiJsonExtensions
{

    /// <summary>Global JsonSerializerOptions for FFI marshalling with relaxed numeric handling.
    /// Supports: enum-to-snake_case conversion, ignoring default values, and reading numeric values from strings.
    /// Used by both trait bridges and callback deserialization.</summary>
    public static readonly JsonSerializerOptions FfiJsonOptions = new()
    {
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        NumberHandling = JsonNumberHandling.AllowReadingFromString
    };

    /// <summary>Serialize any object to JSON for FFI marshalling</summary>
    internal static string ToFfiJson<T>(this T value)
    {
        return JsonSerializer.Serialize(value, FfiJsonOptions);
    }

}
