// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2f75d27e06f0e4aebd1c2e05cd856d3ff3ac66ffb193aaebd2edc9c29eb3ed17
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; private set; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }

    public HtmlToMarkdownRsException(string message) : base(message)
    {
        Code = 0;
    }

    public HtmlToMarkdownRsException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }

    private static HtmlToMarkdownRsException WithNativeCode(HtmlToMarkdownRsException exception, int code)
    {
        exception.Code = code;
        return exception;
    }

    /// <summary>
    /// Builds the concrete exception for the FFI's current thread-local last-error state,
    /// dispatching to the specific per-variant exception class when the message's prefix
    /// identifies a known variant. Every throw site across the generated binding funnels
    /// through here so a variant's identity is never lost to a bypassed dispatch.
    /// </summary>
    internal static Exception FromLastError(string fallbackMessage)
    {
        var code = NativeMethods.LastErrorCode();
        var ctxPtr = NativeMethods.LastErrorContext();
        var message = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(ctxPtr) ?? fallbackMessage;
        if (message.StartsWith("Invalid configuration:")) return WithNativeCode(new ConfigErrorException(message), code);
        if (message.StartsWith("HTML parsing error:")) return WithNativeCode(new ParseErrorException(message), code);
        if (message.StartsWith("Sanitization error:")) return WithNativeCode(new SanitizationErrorException(message), code);
        if (message.StartsWith("Conversion error:")) return WithNativeCode(new OtherException(message), code);
        if (message.StartsWith("Internal panic:")) return WithNativeCode(new PanicException(message), code);
        if (message.StartsWith("Invalid input:")) return WithNativeCode(new InvalidInputException(message), code);
        if (message.StartsWith("I/O error:")) return WithNativeCode(new IoErrorException(message), code);
        if (code == 2) return WithNativeCode(new ConversionErrorException(message), code);
        return new HtmlToMarkdownRsException(code, message);
    }
}
